
package org.tempuri;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.interbankfundtransfers.NIPCheckResponse;
import org.datacontract.schemas._2004._07.interbankfundtransfers.SchemeCharge;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PostBridgeSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    org.tempuri.ObjectFactory.class,
    org.datacontract.schemas._2004._07.system_collections.ObjectFactory.class,
    org.datacontract.schemas._2004._07.interbankfundtransfers.ObjectFactory.class
})
public interface PostBridgeSoap {


    /**
     * 
     * @param amount
     * @param fromAcc
     * @param narration
     * @param toAcc
     * @param xHeader
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PostTransaction", action = "http://tempuri.org/PostTransaction")
    @WebResult(name = "PostTransactionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PostTransaction", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostTransaction")
    @ResponseWrapper(localName = "PostTransactionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostTransactionResponse")
    public String postTransaction(
        @WebParam(name = "FromAcc", targetNamespace = "http://tempuri.org/")
        String fromAcc,
        @WebParam(name = "ToAcc", targetNamespace = "http://tempuri.org/")
        String toAcc,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount,
        @WebParam(name = "Narration", targetNamespace = "http://tempuri.org/")
        String narration,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param amount
     * @param traceID
     * @param fromAcc
     * @param narration
     * @param toAcc
     * @param xHeader
     * @return
     *     returns org.tempuri.PaymentResponse
     */
    @WebMethod(operationName = "PostTrans", action = "http://tempuri.org/PostTrans")
    @WebResult(name = "PostTransResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PostTrans", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostTrans")
    @ResponseWrapper(localName = "PostTransResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostTransResponse")
    public PaymentResponse postTrans(
        @WebParam(name = "FromAcc", targetNamespace = "http://tempuri.org/")
        String fromAcc,
        @WebParam(name = "ToAcc", targetNamespace = "http://tempuri.org/")
        String toAcc,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount,
        @WebParam(name = "Narration", targetNamespace = "http://tempuri.org/")
        String narration,
        @WebParam(name = "TraceID", targetNamespace = "http://tempuri.org/")
        String traceID,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param amount
     * @param traceID
     * @param fromAcc
     * @param narration
     * @param toAcc
     * @param fromCustID
     * @param xHeader
     * @return
     *     returns org.tempuri.PaymentResponse
     */
    @WebMethod(operationName = "PostTransact", action = "http://tempuri.org/PostTransact")
    @WebResult(name = "PostTransactResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PostTransact", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostTransact")
    @ResponseWrapper(localName = "PostTransactResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostTransactResponse")
    public PaymentResponse postTransact(
        @WebParam(name = "FromCustID", targetNamespace = "http://tempuri.org/")
        String fromCustID,
        @WebParam(name = "FromAcc", targetNamespace = "http://tempuri.org/")
        String fromAcc,
        @WebParam(name = "ToAcc", targetNamespace = "http://tempuri.org/")
        String toAcc,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount,
        @WebParam(name = "Narration", targetNamespace = "http://tempuri.org/")
        String narration,
        @WebParam(name = "TraceID", targetNamespace = "http://tempuri.org/")
        String traceID,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param tran
     * @param xHeader
     * @return
     *     returns org.tempuri.PaymentResponse
     */
    @WebMethod(operationName = "PostTransRequest", action = "http://tempuri.org/PostTransRequest")
    @WebResult(name = "PostTransRequestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PostTransRequest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostTransRequest")
    @ResponseWrapper(localName = "PostTransRequestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostTransRequestResponse")
    public PaymentResponse postTransRequest(
        @WebParam(name = "tran", targetNamespace = "http://tempuri.org/")
        PaymentRequest tran,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param amount
     * @param traceID
     * @param charges
     * @param fromAcc
     * @param narration
     * @param toAcc
     * @param xHeader
     * @param bankCode
     * @return
     *     returns org.tempuri.PaymentCustomAccountChargeResponse
     */
    @WebMethod(operationName = "PostFIPCustomAccountCharges", action = "http://tempuri.org/PostFIPCustomAccountCharges")
    @WebResult(name = "PostFIPCustomAccountChargesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PostFIPCustomAccountCharges", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostFIPCustomAccountCharges")
    @ResponseWrapper(localName = "PostFIPCustomAccountChargesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostFIPCustomAccountChargesResponse")
    public PaymentCustomAccountChargeResponse postFIPCustomAccountCharges(
        @WebParam(name = "FromAcc", targetNamespace = "http://tempuri.org/")
        String fromAcc,
        @WebParam(name = "ToAcc", targetNamespace = "http://tempuri.org/")
        String toAcc,
        @WebParam(name = "BankCode", targetNamespace = "http://tempuri.org/")
        String bankCode,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount,
        @WebParam(name = "Narration", targetNamespace = "http://tempuri.org/")
        String narration,
        @WebParam(name = "Charges", targetNamespace = "http://tempuri.org/")
        CustomAccountCharges charges,
        @WebParam(name = "TraceID", targetNamespace = "http://tempuri.org/")
        String traceID,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param amount
     * @param traceID
     * @param charges
     * @param fromAcc
     * @param narration
     * @param toAcc
     * @param xHeader
     * @param bankCode
     * @return
     *     returns org.tempuri.PaymentCustomChargeResponse
     */
    @WebMethod(operationName = "PostFIPCustomCharges", action = "http://tempuri.org/PostFIPCustomCharges")
    @WebResult(name = "PostFIPCustomChargesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PostFIPCustomCharges", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostFIPCustomCharges")
    @ResponseWrapper(localName = "PostFIPCustomChargesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostFIPCustomChargesResponse")
    public PaymentCustomChargeResponse postFIPCustomCharges(
        @WebParam(name = "FromAcc", targetNamespace = "http://tempuri.org/")
        String fromAcc,
        @WebParam(name = "ToAcc", targetNamespace = "http://tempuri.org/")
        String toAcc,
        @WebParam(name = "BankCode", targetNamespace = "http://tempuri.org/")
        String bankCode,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount,
        @WebParam(name = "Narration", targetNamespace = "http://tempuri.org/")
        String narration,
        @WebParam(name = "Charges", targetNamespace = "http://tempuri.org/")
        CustomCharges charges,
        @WebParam(name = "TraceID", targetNamespace = "http://tempuri.org/")
        String traceID,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param amount
     * @param traceID
     * @param charges
     * @param fromAcc
     * @param narration
     * @param phoneNumber
     * @param xHeader
     * @param bankCode
     * @return
     *     returns org.tempuri.PaymentWalletResponse
     */
    @WebMethod(operationName = "PostFIPWallet", action = "http://tempuri.org/PostFIPWallet")
    @WebResult(name = "PostFIPWalletResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PostFIPWallet", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostFIPWallet")
    @ResponseWrapper(localName = "PostFIPWalletResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostFIPWalletResponse")
    public PaymentWalletResponse postFIPWallet(
        @WebParam(name = "FromAcc", targetNamespace = "http://tempuri.org/")
        String fromAcc,
        @WebParam(name = "PhoneNumber", targetNamespace = "http://tempuri.org/")
        String phoneNumber,
        @WebParam(name = "BankCode", targetNamespace = "http://tempuri.org/")
        String bankCode,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount,
        @WebParam(name = "Narration", targetNamespace = "http://tempuri.org/")
        String narration,
        @WebParam(name = "Charges", targetNamespace = "http://tempuri.org/")
        CustomAccountCharges charges,
        @WebParam(name = "TraceID", targetNamespace = "http://tempuri.org/")
        String traceID,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param tran
     * @param xHeader
     * @return
     *     returns org.tempuri.PaymentResponse
     */
    @WebMethod(operationName = "PostTransReq", action = "http://tempuri.org/PostTransReq")
    @WebResult(name = "PostTransReqResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PostTransReq", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostTransReq")
    @ResponseWrapper(localName = "PostTransReqResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostTransReqResponse")
    public PaymentResponse postTransReq(
        @WebParam(name = "tran", targetNamespace = "http://tempuri.org/")
        PayReq tran,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param refNum
     * @param xHeader
     * @return
     *     returns org.tempuri.PaymentResponse
     */
    @WebMethod(operationName = "PostReversalByRefNo", action = "http://tempuri.org/PostReversalByRefNo")
    @WebResult(name = "PostReversalByRefNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PostReversalByRefNo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostReversalByRefNo")
    @ResponseWrapper(localName = "PostReversalByRefNoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostReversalByRefNoResponse")
    public PaymentResponse postReversalByRefNo(
        @WebParam(name = "ref_num", targetNamespace = "http://tempuri.org/")
        String refNum,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param refNum
     * @param xHeader
     * @return
     *     returns org.tempuri.PaymentResponseWithCharge
     */
    @WebMethod(operationName = "ReversalByRefNo", action = "http://tempuri.org/ReversalByRefNo")
    @WebResult(name = "ReversalByRefNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReversalByRefNo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReversalByRefNo")
    @ResponseWrapper(localName = "ReversalByRefNoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReversalByRefNoResponse")
    public PaymentResponseWithCharge reversalByRefNo(
        @WebParam(name = "ref_num", targetNamespace = "http://tempuri.org/")
        String refNum,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param traceId
     * @param xHeader
     * @return
     *     returns org.tempuri.PaymentResponse
     */
    @WebMethod(operationName = "PostReversalByTraceID", action = "http://tempuri.org/PostReversalByTraceID")
    @WebResult(name = "PostReversalByTraceIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PostReversalByTraceID", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostReversalByTraceID")
    @ResponseWrapper(localName = "PostReversalByTraceIDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostReversalByTraceIDResponse")
    public PaymentResponse postReversalByTraceID(
        @WebParam(name = "trace_id", targetNamespace = "http://tempuri.org/")
        String traceId,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @return
     *     returns org.tempuri.ArrayOfBank
     */
    @WebMethod(operationName = "GetBanks", action = "http://tempuri.org/GetBanks")
    @WebResult(name = "GetBanksResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBanks", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBanks")
    @ResponseWrapper(localName = "GetBanksResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBanksResponse")
    public ArrayOfBank getBanks();

    /**
     * 
     * @return
     *     returns org.tempuri.ArrayOfString
     */
    @WebMethod(operationName = "GetAllSchemes", action = "http://tempuri.org/GetAllSchemes")
    @WebResult(name = "GetAllSchemesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllSchemes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllSchemes")
    @ResponseWrapper(localName = "GetAllSchemesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllSchemesResponse")
    public ArrayOfString getAllSchemes();

    /**
     * 
     * @param request
     * @param xHeader
     * @return
     *     returns org.tempuri.WalletNameEnquiryResponse2
     */
    @WebMethod(operationName = "WalletNameEnquiry", action = "http://tempuri.org/WalletNameEnquiry")
    @WebResult(name = "WalletNameEnquiryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "WalletNameEnquiry", targetNamespace = "http://tempuri.org/", className = "org.tempuri.WalletNameEnquiry")
    @ResponseWrapper(localName = "WalletNameEnquiryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.WalletNameEnquiryResponse")
    public WalletNameEnquiryResponse2 walletNameEnquiry(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        WalletNameEnquiryRequest request,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.interbankfundtransfers.SchemeCharge
     */
    @WebMethod(operationName = "GetSchemeCharges", action = "http://tempuri.org/GetSchemeCharges")
    @WebResult(name = "GetSchemeChargesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSchemeCharges", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSchemeCharges")
    @ResponseWrapper(localName = "GetSchemeChargesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSchemeChargesResponse")
    public SchemeCharge getSchemeCharges(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        GetSchemeChargesRequest request);

    /**
     * 
     * @param amount
     * @return
     *     returns org.datacontract.schemas._2004._07.interbankfundtransfers.SchemeCharge
     */
    @WebMethod(operationName = "GetBranchSchemeCharges", action = "http://tempuri.org/GetBranchSchemeCharges")
    @WebResult(name = "GetBranchSchemeChargesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBranchSchemeCharges", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBranchSchemeCharges")
    @ResponseWrapper(localName = "GetBranchSchemeChargesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBranchSchemeChargesResponse")
    public SchemeCharge getBranchSchemeCharges(
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount);

    /**
     * 
     * @param traceId
     * @param xHeader
     * @return
     *     returns org.tempuri.ArrayOfPaymentResponse
     */
    @WebMethod(operationName = "QueryTransaction", action = "http://tempuri.org/QueryTransaction")
    @WebResult(name = "QueryTransactionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryTransaction", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryTransaction")
    @ResponseWrapper(localName = "QueryTransactionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryTransactionResponse")
    public ArrayOfPaymentResponse queryTransaction(
        @WebParam(name = "trace_id", targetNamespace = "http://tempuri.org/")
        String traceId,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param amount
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "GetInterBankCharge", action = "http://tempuri.org/GetInterBankCharge")
    @WebResult(name = "GetInterBankChargeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInterBankCharge", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInterBankCharge")
    @ResponseWrapper(localName = "GetInterBankChargeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInterBankChargeResponse")
    public BigDecimal getInterBankCharge(
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount);

    /**
     * 
     * @param accountNumber
     * @param xHeader
     * @return
     *     returns org.tempuri.AccountBalanceObj
     */
    @WebMethod(operationName = "GetAccountBalance", action = "http://tempuri.org/GetAccountBalance")
    @WebResult(name = "GetAccountBalanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAccountBalance", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAccountBalance")
    @ResponseWrapper(localName = "GetAccountBalanceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAccountBalanceResponse")
    public AccountBalanceObj getAccountBalance(
        @WebParam(name = "AccountNumber", targetNamespace = "http://tempuri.org/")
        String accountNumber,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param amount
     * @param accountNumber
     * @param xHeader
     * @return
     *     returns org.datacontract.schemas._2004._07.interbankfundtransfers.NIPCheckResponse
     */
    @WebMethod(operationName = "NIPCheckMethod", action = "http://tempuri.org/NIPCheckMethod")
    @WebResult(name = "NIPCheckMethodResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NIPCheckMethod", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NIPCheckMethod")
    @ResponseWrapper(localName = "NIPCheckMethodResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NIPCheckMethodResponse")
    public NIPCheckResponse nipCheckMethod(
        @WebParam(name = "AccountNumber", targetNamespace = "http://tempuri.org/")
        String accountNumber,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param request
     * @param xHeader
     * @return
     *     returns org.tempuri.NameEnquiryResponse2
     */
    @WebMethod(operationName = "NameEnquiry", action = "http://tempuri.org/NameEnquiry")
    @WebResult(name = "NameEnquiryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NameEnquiry", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NameEnquiry")
    @ResponseWrapper(localName = "NameEnquiryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NameEnquiryResponse")
    public NameEnquiryResponse2 nameEnquiry(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        NameEnquiryRequest request,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param amount
     * @param beneficiaryBankCode
     * @param narration
     * @param xHeader
     * @param beneficiaryAcc
     * @param sourceAcc
     * @return
     *     returns org.tempuri.NAPSNeftRequestResponse
     */
    @WebMethod(operationName = "PostNEFTNAPS", action = "http://tempuri.org/PostNEFTNAPS")
    @WebResult(name = "PostNEFTNAPSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PostNEFTNAPS", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostNEFTNAPS")
    @ResponseWrapper(localName = "PostNEFTNAPSResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostNEFTNAPSResponse")
    public NAPSNeftRequestResponse postNEFTNAPS(
        @WebParam(name = "SourceAcc", targetNamespace = "http://tempuri.org/")
        String sourceAcc,
        @WebParam(name = "BeneficiaryAcc", targetNamespace = "http://tempuri.org/")
        String beneficiaryAcc,
        @WebParam(name = "BeneficiaryBankCode", targetNamespace = "http://tempuri.org/")
        String beneficiaryBankCode,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount,
        @WebParam(name = "Narration", targetNamespace = "http://tempuri.org/")
        String narration,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param tranRefNo
     * @param xHeader
     * @return
     *     returns org.tempuri.NAPSNeftEnquiryResponse
     */
    @WebMethod(operationName = "NeftNapsEnquiry", action = "http://tempuri.org/NeftNapsEnquiry")
    @WebResult(name = "NeftNapsEnquiryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NeftNapsEnquiry", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NeftNapsEnquiry")
    @ResponseWrapper(localName = "NeftNapsEnquiryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NeftNapsEnquiryResponse")
    public NAPSNeftEnquiryResponse neftNapsEnquiry(
        @WebParam(name = "TranRefNo", targetNamespace = "http://tempuri.org/")
        String tranRefNo,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

    /**
     * 
     * @param chargeAmount
     * @param amount
     * @param traceID
     * @param fromAcc
     * @param narration
     * @param toAcc
     * @param xHeader
     * @return
     *     returns org.tempuri.PaymentResponseWithCharge
     */
    @WebMethod(operationName = "PostTransWithCharge", action = "http://tempuri.org/PostTransWithCharge")
    @WebResult(name = "PostTransWithChargeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PostTransWithCharge", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostTransWithCharge")
    @ResponseWrapper(localName = "PostTransWithChargeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PostTransWithChargeResponse")
    public PaymentResponseWithCharge postTransWithCharge(
        @WebParam(name = "FromAcc", targetNamespace = "http://tempuri.org/")
        String fromAcc,
        @WebParam(name = "ToAcc", targetNamespace = "http://tempuri.org/")
        String toAcc,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        BigDecimal amount,
        @WebParam(name = "Narration", targetNamespace = "http://tempuri.org/")
        String narration,
        @WebParam(name = "chargeAmount", targetNamespace = "http://tempuri.org/")
        ArrayOfKeyValuePairOfDecimalString chargeAmount,
        @WebParam(name = "TraceID", targetNamespace = "http://tempuri.org/")
        String traceID,
        @WebParam(name = "xHeader", targetNamespace = "http://tempuri.org/", header = true, mode = WebParam.Mode.INOUT, partName = "xHeader")
        Holder<XHeader> xHeader);

}
